config/routes.rb
EEGM::Application.routes.draw do
  get "system_updates/index"
  resources :system_configs

  resources :activities
  

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get "purchase_orders/reload_purchase_item/:purchase_item_id" => 'purchase_orders#reload_purchase_item', as: 'reload_purchase_item'
  get "purchase_orders/reload_purchase_item" => 'purchase_orders#reload_purchase_item', as: 'partial_reload_purchase_item'

  get "purchase_orders/update_purchase_items" => 'purchase_orders#update_purchase_items', as: 'partial_update_purchase_items'
  get "purchase_orders/update_purchase_items/:item_delivery_id" => 'purchase_orders#update_purchase_items', as: 'update_purchase_items'
  get "purchase_items/index"
  get "purchase_items/new"
  get "purchase_items/create"
  get "purchase_items/destroy"
  get "purchase_items/update"
  get "purchase_order_contacts/index"
  get "purchase_order_contacts/new"
  get "purchase_order_contacts/create"
  get "purchase_order_contacts/destroy"
  get "purchase_order_contacts/update"
  resources :item_deliveries

  resources :purchase_orders do
    get 'status/:po_status' => "purchase_orders#index", on: :collection, as: 'status'
    get 'print' => 'purchase_orders#print', on: :member
  end

  resources :supplier_items

  resources :items

  resources :suppliers do
    get 'summary', on: :member
  end

  resources :contacts

  resources :phones

  resources :purchase_order_contacts

  resources :purchase_items do
  end

  get 'suppliers/:id/summary/:po_status' => "suppliers#summary", as: 'summary_by_status_supplier'

  get 'latest/price/name', to: 'purchase_items#index', as: 'last_price_purchase_item_name'
  get 'purchase_item/last', to: 'purchase_items#last', as: 'partial_last_purchase_item'
  get 'purchase_item/last/:item_id', to: 'purchase_items#last', as: 'last_purchase_item'

  get 'supplier/names', to: 'suppliers#names'
  get 'contact/names', to: 'contacts#names'
  get 'item/names', to: 'items#names'
  get 'phone/numbers', to: 'phones#numbers'

  root 'purchase_orders#index'

end

app/models/item_delivery.rb
class ItemDelivery < ActiveRecord::Base
include PublicActivity::Common

  belongs_to :item
  belongs_to :purchase_order

  validates :item, presence: {message: "does not exist."}

  def delivery_complete?
    purchase_order.completed?(item)
  end

  def delivery_count
    purchase_order.count_delivery_item(item) if purchase_order
  end

  def date_received_long
  	date_recieved.to_time.to_s(:long)
  end

  def date_received_med
  	date_recieved.to_time.to_s(:med)
  end

  def details
    "#{purchase_order.details} - Delivery ##{id}[#{to_s}]"
  end

  def to_s
  	"#{item.name} - #{quantity} #{unit} #{date_received_med}" if item
  end

  def item_name
  	item.try :name
  end

  def item_name=(name)
  	# self.item = Item.find_by(name: name) if name
    self.item = Item.where("lower(name) = ?", name.downcase).first if name
    # if name
    #   self.item Item.find(:name, :conditions => ["lower(name) = ?", name.downcase])
    # end
  end

  def record_activity(action, current_user, description)
    create_activity action, 
        owner: current_user, 
        recipient: self.purchase_order,
        parameters: {
        description: description,
        details: self.details}
  end

  def record_update(current_user, params)
    create_activity :update, 
        owner: current_user, 
        recipient: self.purchase_order,
        parameters: {
        description: "Updated PO Delivery Item",
        details: "#{purchase_order.details} - Delivery ##{id}[#{params}]"
      }
  end

end

app/controllers/item_deliveries_controller.rb
class ItemDeliveriesController < ApplicationController
  before_action :set_item_delivery, only: [:show, :edit, :update, :destroy]

  # GET /item_deliveries
  # GET /item_deliveries.json
  def index
    @item_deliveries = ItemDelivery.all
  end

  # GET /item_deliveries/1
  # GET /item_deliveries/1.json
  def show
  end

  # GET /item_deliveries/new
  def new
    @item_delivery = ItemDelivery.new
  end

  # GET /item_deliveries/1/edit
  def edit
  end

  # POST /item_deliveries
  # POST /item_deliveries.json
  def create
    @item_delivery = ItemDelivery.new(item_delivery_params)
    @item_name = item_delivery_params[:item_name]
    
    puts "Item name [#{@item_delivery.item_name}], Item: #{@item_delivery.item}"

    respond_to do |format|
      if @item_delivery.save
        @item_delivery.record_activity(:create, current_user, "Add PO Delivery")
        format.html { redirect_to @item_delivery.purchase_order, notice: 'Item delivery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item_delivery }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @item_delivery.errors, status: :unprocessable_entity }
        format.js { render 'error' }
      end
    end
  end

  # PATCH/PUT /item_deliveries/1
  # PATCH/PUT /item_deliveries/1.json
  def update
    respond_to do |format|
      if @item_delivery.update(item_delivery_params)
        @item_delivery.record_activity(:update, current_user, "Updated PO Delivery")
        format.html { redirect_to @item_delivery, notice: 'Item delivery was successfully updated.' }
        format.json { respond_with_bip @item_delivery }
      else
        format.html { render action: 'edit' }
        format.json { respond_with_bip @item_delivery }
      end
    end
  end

  # DELETE /item_deliveries/1
  # DELETE /item_deliveries/1.json
  def destroy
    @item_delivery.record_activity(:delete, current_user, "Deleted PO Delivery")
    po = @item_delivery.purchase_order
    @item_delivery_id = @item_delivery.id
    @item_delivery.destroy
    respond_to do |format|
      format.html { redirect_to purchase_order_path(po) }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_delivery
      @item_delivery = ItemDelivery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_delivery_params
      params.require(:item_delivery).permit(:item_id, :item_name, :purchase_order_id, :quantity, :unit, :date_recieved)
    end
end

app/helpers/item_deliveries_helper.rb
module ItemDeliveriesHelper
end

app/views/item_deliveries/_form.html.erb
<%= form_for(@item_delivery) do |f| %>
  <% if @item_delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_delivery.errors.count, "error") %> prohibited this item_delivery from being saved:</h2>

      <ul>
      <% @item_delivery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td><%= f.label :item_name %></td>
    <td><%= f.label :quantity %></td>
    <td><%= f.label :unit %></td>
    <td><%= f.label :date_recieved %></td>
    <td></td>
  </tr>

  <tr>
    <td class="item_name"><%= f.text_field :item_name, data: {autocomplete_source: item_names_path}%></td>
    <td><%= f.number_field :quantity %></td>
    <td><%= f.text_field :unit %></td>
    <td><%= f.text_field :date_recieved %></td>
    <td></td>
  </tr>
</table>
<%= f.hidden_field :purchase_order_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_deliveries/_item_delivery.html.erb
<tr id="item_delivery_<%=item_delivery.id%>">
  <td class="item_name"><%=item_delivery.item_name%></td>
  <td class="item_quantity_column"><%=best_in_place item_delivery, :quantity, display_with: :number_with_delimiter%></td>
  <td><%=best_in_place item_delivery, :unit%></td>
  <td><%=best_in_place item_delivery, :date_recieved, type: :date, display_as: :date_received_long%></td>
  <td><%= link_to 'X', item_delivery, method: :delete, data: { confirm: "Delete Delivery '#{item_delivery.item_name} x #{number_with_delimiter item_delivery.quantity} #{item_delivery.unit}'?" }, remote: true, class: "remove_fields" %></td>
</tr>

app/views/item_deliveries/_item_delivery_count.js.erb
<% if item_delivery.item %>
	$('#<%=item_delivery.item.css_id%>').html('<%=item_delivery.delivery_count%>').closest('tr').effect("highlight");
	<% if item_delivery.delivery_complete? %>
		$('#<%=item_delivery.item.css_id%>').html('<%=item_delivery.delivery_count%>').closest('tr').addClass("completed");
	<% else %>
		$('#<%=item_delivery.item.css_id%>').html('<%=item_delivery.delivery_count%>').closest('tr').removeClass("completed");
	<% end %>
<% end %>

app/views/item_deliveries/create.js.erb
$('#error_explanation').remove();
$('#notice').empty().append("<%= flash[:create_notice] %>");
$('#item_delivery_item_name').val("").focus();
initItemDeliveryDate();
$('#new_item_delivery_row').after("<%= j render @item_delivery%>");
$('.adding_item_delivery:first').remove();
$('#item_delivery_<%=@item_delivery.id%> a.remove_fields').add_pending_deletion_class_to_closes_tr_on_click();
<%=render 'item_delivery_count', item_delivery: @item_delivery%>
$('#item_delivery_<%=@item_delivery.id%> .best_in_place').bind("ajax:success", update_item);

app/views/item_deliveries/destroy.js.erb
<%=render 'item_delivery_count', item_delivery: @item_delivery%>
$('#item_delivery_<%=@item_delivery_id%>').fadeOut('slow', function(){
        $(this).remove();
});

app/views/item_deliveries/edit.html.erb
<h1>Editing item_delivery</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_delivery %> |
<%= link_to 'Back', item_deliveries_path %>

app/views/item_deliveries/error.js.erb
$('.adding_item_delivery:first td').html('');
$('.adding_item_delivery:first').addClass('error_explanation');

<% @item_delivery.errors.full_messages.each do | error | %>
$('.adding_item_delivery:first td').append('<li><%="Unable to save '#{@item_name}'. #{error}"%></li>');
<% end %>


setTimeout(function() {
	$('.adding_item_delivery:first').fadeOut('slow', function() {
		$('.adding_item_delivery:first').remove();
	});
},20000);

app/views/item_deliveries/index.html.erb
<h1>Listing item_deliveries</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Purchase order</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th>Date recieved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @item_deliveries.each do |item_delivery| %>
      <tr>
        <td><%= item_delivery.item %></td>
        <td><%= item_delivery.purchase_order %></td>
        <td><%= item_delivery.quantity %></td>
        <td><%= item_delivery.unit %></td>
        <td><%= item_delivery.date_recieved %></td>
        <td><%= link_to 'Show', item_delivery %></td>
        <td><%= link_to 'Edit', edit_item_delivery_path(item_delivery) %></td>
        <td><%= link_to 'Destroy', item_delivery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item delivery', new_item_delivery_path %>

app/views/item_deliveries/new.html.erb
<h1>New item_delivery</h1>

<%= render 'form' %>

<%= link_to 'Back', item_deliveries_path %>

app/views/item_deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_delivery.item %>
</p>

<p>
  <strong>Purchase order:</strong>
  <%= @item_delivery.purchase_order %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item_delivery.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @item_delivery.unit %>
</p>

<p>
  <strong>Date recieved:</strong>
  <%= @item_delivery.date_recieved %>
</p>

<%= link_to 'Edit', edit_item_delivery_path(@item_delivery) %> |
<%= link_to 'Back', item_deliveries_path %>