config/routes.rb
EEGM::Application.routes.draw do
  get "system_updates/index"
  resources :system_configs

  resources :activities
  

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get "purchase_orders/reload_purchase_item/:purchase_item_id" => 'purchase_orders#reload_purchase_item', as: 'reload_purchase_item'
  get "purchase_orders/reload_purchase_item" => 'purchase_orders#reload_purchase_item', as: 'partial_reload_purchase_item'

  get "purchase_orders/update_purchase_items" => 'purchase_orders#update_purchase_items', as: 'partial_update_purchase_items'
  get "purchase_orders/update_purchase_items/:item_delivery_id" => 'purchase_orders#update_purchase_items', as: 'update_purchase_items'
  get "purchase_items/index"
  get "purchase_items/new"
  get "purchase_items/create"
  get "purchase_items/destroy"
  get "purchase_items/update"
  get "purchase_order_contacts/index"
  get "purchase_order_contacts/new"
  get "purchase_order_contacts/create"
  get "purchase_order_contacts/destroy"
  get "purchase_order_contacts/update"
  resources :item_deliveries

  resources :purchase_orders do
    get 'status/:po_status' => "purchase_orders#index", on: :collection, as: 'status'
    get 'print' => 'purchase_orders#print', on: :member
  end

  resources :supplier_items

  resources :items

  resources :suppliers do
    get 'summary', on: :member
  end

  resources :contacts

  resources :phones

  resources :purchase_order_contacts

  resources :purchase_items do
  end

  get 'suppliers/:id/summary/:po_status' => "suppliers#summary", as: 'summary_by_status_supplier'

  get 'latest/price/name', to: 'purchase_items#index', as: 'last_price_purchase_item_name'
  get 'purchase_item/last', to: 'purchase_items#last', as: 'partial_last_purchase_item'
  get 'purchase_item/last/:item_id', to: 'purchase_items#last', as: 'last_purchase_item'

  get 'supplier/names', to: 'suppliers#names'
  get 'contact/names', to: 'contacts#names'
  get 'item/names', to: 'items#names'
  get 'phone/numbers', to: 'phones#numbers'

  root 'purchase_orders#index'

end

app/models/purchase_order.rb
include ActionView::Helpers::NumberHelper

class PurchaseOrder < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :supplier
  has_many :phones, as: :contact_detail, :dependent => :delete_all
  has_many :purchase_order_contacts, :dependent => :delete_all
  has_many :purchase_items, :dependent => :delete_all
  has_many :item_deliveries, :dependent => :delete_all
  has_many :items, through: :purchase_items

  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :purchase_order_contacts, allow_destroy: true
  accepts_nested_attributes_for :purchase_items, allow_destroy: true

  after_save :copy_phone unless :phones.empty?
  after_save :copy_contact unless :purchase_order_contacts.empty?

  validates :supplier, presence: true

  scope :pending, -> {where(status: 'PENDING').order(po_date: :desc)}
  scope :confirmed, -> {where(status: 'CONFIRMED').order(po_date: :desc)}
  scope :delivered, -> {where(status: 'DELIVERED').order(po_date: :desc)}
  scope :cancelled, -> {where(status: 'CANCELLED').order(po_date: :desc)}

  def completed?(item)
    count_delivery_item(item) >= count_item_order(item)
  end

  def count_item_order(item)
    if purchase_items
      purchase_items.where(item: item).sum(:quantity)
    else
      0
    end
  end

  def count_delivery_item(item)
    if item_deliveries
      item_deliveries.where(item: item).sum(:quantity)
    else
      0
    end
  end

  def po_id
    sprintf('%07d', id)
  end

  def details
    "PO##{po_id} #{po_date.to_time.to_s(:med) if po_date} #{supplier.try :name}"
  end

  def po_date_long_format
    po_date.to_time.to_s(:long)
  end

  def grand_total_formatted
    number_with_delimiter number_with_precision(self.grand_total, precision: 2)
  end

  def grand_total_formatted=(grand_total_formatted)
    self.grand_total = grand_total_formatted.delete ","
  end

  def supplier_name
  	supplier.try :name
  end

  def supplier_name=(name)
  	self.supplier = Supplier.find_or_create_by(name: name) if name.present?
  end

  def copy_phone
    phones.each do | phone |
      supplier.phones.create(number: phone.number) if supplier.phones.where(number: phone.number).empty?
    end
  end

  def copy_contact
    purchase_order_contacts.each do | contact |
      Contact.new(name: contact.name).save if Contact.where(name: contact.name).empty?
    end
  end

  def items_description

    desc = ""

    purchase_items.each do | item |
      desc += item.to_s + ", " if item
    end

    desc
  end

  def record_activity(action, current_user, description)
    create_activity action, 
        owner: current_user, 
        recipient: self,
        parameters: {
        description: description,
        details: self.details}
  end

  def record_update(current_user, params)
    create_activity :update, 
        owner: current_user, 
        recipient: self,
        parameters: {
        description: "Updated PO",
        details: "#{self.details} #{params}"
      }
  end

  def purchase_items_cache_key
    "#{cache_key}-#{pi_key}-#{di_key}"
  end

  def item_deliveries_cache_key
    "#{cache_key}-#{di_key}"
  end

  def di_key
    "di/#{generic_cache_key(item_deliveries)}"
  end

  def pi_key
    "pi/#{generic_cache_key(purchase_items)}"
  end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_purchase_order, only: [:print, :show, :edit, :update, :destroy]

  def reload_purchase_item
    purchase_item_id = params[:purchase_item_id]
    if purchase_item_id
      @purchase_item = PurchaseItem.find(purchase_item_id)
    end

    respond_to do |format|
      format.js
    end
  end


  def update_purchase_items
    item_delivery_id = params[:item_delivery_id]
    if item_delivery_id
      @item_delivery = ItemDelivery.find(item_delivery_id)
    end

    respond_to do |format|
      format.js
    end
  end

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @po_status = params[:po_status] || 'PENDING'
    @item_name = params[:item_name]

    if @po_status == 'ALL'
      @purchase_orders = PurchaseOrder.all.order(po_date: :desc)
    else
      @purchase_orders = PurchaseOrder.where(status: @po_status).order(po_date: :desc)
    end

    
    if @item_name
       @purchase_orders = @purchase_orders.where("id in (select purchase_order_id from purchase_items where item_id in (select id from items where name like '%#{@item_name}%'))")
    end


    @new_purchase_order = PurchaseOrder.new
    @new_purchase_order.po_date = Date.today
    @new_purchase_order.status = 'PENDING'

  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
    @item_delivery = ItemDelivery.new
    @item_delivery.purchase_order = @purchase_order
    @item_delivery.date_recieved = Date.today

    @new_purchase_order_contact = PurchaseOrderContact.new(purchase_order: @purchase_order)
    @new_phone = Phone.new(contact_detail_type: @purchase_order.class, contact_detail_id: @purchase_order.id)

    @new_purchase_item = PurchaseItem.new(purchase_order: @purchase_order)
  end

  def print
    show

    @mobile = SystemConfig.find_by_name('store_mobile_number')
    @landline = SystemConfig.find_by_name('store_landline_number')
    @fax = SystemConfig.find_by_name('store_fax_number')
    @email = SystemConfig.find_by_name('store_email')


    render layout: false
  end


  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
    @purchase_order.purchase_order_contacts.build
    @purchase_order.phones.build
    @purchase_order.purchase_items.build
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)
    @purchase_order.username = current_user.username

    #Copy Contact Details from last purchase order
    unless purchase_order_params[:purchase_order_contact]
      supplier = Supplier.find_by(name: purchase_order_params[:supplier_name])
      if supplier
        similar_pos = PurchaseOrder.where(supplier: supplier).last

        if similar_pos
          similar_pos.purchase_order_contacts.each do | c |
            @purchase_order.purchase_order_contacts.build name: c.name
          end
          similar_pos.phones.each do | p |
            @purchase_order.phones.build number: p.number
          end
        end
      end
    end

    respond_to do |format|
      if @purchase_order.save
        @purchase_order.record_activity(:create, current_user, "Created PO")
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase_order }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)

        @purchase_order.record_update(current_user, purchase_order_params)
        
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { respond_with_bip @purchase_order }
      else
        format.html { render action: 'edit' }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order.record_activity(:delete, current_user, "Deleted PO")
    @purchase_order.destroy
    respond_to do |format|

      format.html { redirect_to purchase_orders_url, notice: "Purchase Order #{@purchase_order.po_id} has been deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:status, :username, :po_date, :supplier_id, :notes, :supplier_name, :grand_total_formatted,
        phones_attributes: [:id, :number, :_destroy], 
        purchase_order_contacts_attributes: [:id, :name, :_destroy],
        purchase_items_attributes: 
          [:id, :item_name, :price, :quantity, :unit, :total, :note, :_destroy])
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
	def cache_key_for_purchase_order
	    count          = PurchaseOrder.count
	    max_updated_at = PurchaseOrder.maximum(:updated_at).try(:utc).try(:to_s, :number)
	    "purchase_order/all-#{count}-#{max_updated_at}"
	end
end

app/views/purchase_orders/show/_contact_details_section.html.erb
<div id="contact_details_section" class="span-22">

<table class="contact_details">
  <tr>

    <td id="contact_numbers" class="padd_bottom contact_numbers wip">
      <strong>Contact Numbers</strong>
      <ul class='wic'>
        <% @purchase_order.phones.each do | phone | %>
          <%= render phone %>
        <% end %>
      </ul>
      <div class="no-print toggler">
        <%=link_to 'Add', '', id: 'contact_detail_section_add_phone_link', class: 'add_fields no-print'%>
        <%= form_for(@new_phone, remote: true) do |f| %>
              <%= f.text_field :number, class: "contact_numbers" ,data: {autocomplete_source: phone_numbers_path} %>
              <%= f.hidden_field :contact_detail_type%>
              <%= f.hidden_field :contact_detail_id%>
              <%= f.submit "Add", id: 'add_contact_number_submit' %>
              <%= link_to 'Hide', '', id: "hide_new_purchase_order_number_link" %>
        <% end %>
      </div>
    </td>

    <td id="contact_persons" class="contact_persons wip">
      <strong>Contact Persons</strong>
      <ul class="wic">
        <% @purchase_order.purchase_order_contacts.each do | purchase_order_contact | %>
            <%= render purchase_order_contact %>
        <% end %>
      </ul>
        <div class="no-print toggler">
          <%=link_to 'Add', '', id: 'add_contact_person_link', class: 'add_fields no-print'%>
          <%= form_for(@new_purchase_order_contact, remote: true) do |f| %>
                <%= f.text_field :name, class: "contact_persons" ,data: {autocomplete_source: contact_names_path} %>
                <%= f.hidden_field :purchase_order_id%>
                <%= f.submit "Add", id: 'add_contact_person_submit' %>
                <%= link_to 'Hide', '', id: "hide_new_purchase_order_contact_link" %>
          <% end %>
        </div>
    </td>

  </tr>
</table>

</div>

app/views/purchase_orders/show/_item_deliveries_section.html.erb
<% cache @purchase_order.item_deliveries_cache_key do %>

<hr/>

<div id="purchase_order_show_deliveries_section" class="no-print">

<%= link_to 'Show Deliveries', '', id: "add_delivery_link", class: "button_link" %>

<div class="deliveries_section">
         
 <h3 class="titleize">Deliveries</h3>

<%= form_for(@item_delivery, remote: true) do |f| %>


      <table id="purchase_item_table">
      <tr>
        <th class="item_name">Product Code</th>
        <th class="item_quantity_column">Quantity</th>
        <th>Unit</th>
        <th>Date Recieved</th>
        <th></th>
      </tr>

      <tr id="new_item_delivery_row">
        <td class="item_name"><%= f.text_field :item_name, data: {autocomplete_source: item_names_path}%></td>
        <td class="item_quantity_column small_number"><%= f.number_field :quantity, min: 1%></td>
        <td class="med_number"><%= f.text_field :unit%></td>
        <td><%= f.date_field :date_recieved %></td>
        <td><%= f.submit "Add", id: 'item_delivery_submit' %></td>
      </tr>

      <% @purchase_order.item_deliveries.each do | item_delivery | %>
            <%= render item_delivery %>
      <% end %>


    </table>

    <%= f.hidden_field :purchase_order_id %>

<% end %>




  	 <%= link_to 'Hide', '', id: "hide_delivery_section_link", class: "button_link" %>
    </div>
</div>

<% end %>

app/views/purchase_orders/show/_po_details_footer.html.erb
<div id="po_details_footer">
  <div class="span-10">
    <strong>Notes:</strong>
    <span class="small no-print">(click below to edit)</span>
    </br>
    <%= best_in_place @purchase_order, :notes, :type => :textarea, :ok_button => 'Save', :cancel_button => 'Cancel' %>
  </div>
  <div class="span-12 last txt-right">
    Created by: <%=@purchase_order.username || "Not Recorded" %>
  </div>
</div>

app/views/purchase_orders/show/_po_details_header.html.erb
<div id="po_details_header">

  <div class="span-8">
      <label> Purchase Order #<%=@purchase_order.po_id %> </label>
  </div>

  <div class="span-9">
      Status: <label class="<%=@purchase_order.status%>">
      <%=best_in_place @purchase_order, :status, type: :select, 
        collection: po_statuses, :ok_button => 'Save', :cancel_button => 'Cancel'%>
      </label>
  </div>

  <div class="span-5 last">
      <label><%= best_in_place @purchase_order, :po_date, :type => :date, 
          :display_as => :po_date_long_format%> </label>
  </div>


  <hr/>

  <div class="span-11 border">
    <label>Order To: <%= link_to @purchase_order.supplier, 
      summary_supplier_path(@purchase_order.supplier) %> </label>
  </div>

  <div class="span-11 last">
    <label>Order For: E.Estanislao General Merchandize </label>
  </div>

</div>

app/views/purchase_orders/show/_purchase_item_section.html.erb
<% cache @purchase_order.purchase_items_cache_key do %>

<div class="items_section">
  <%= form_for(@new_purchase_item, remote: true) do |f| %>
      <table id="purchase_item_table">
      <tr>
        <th>Product Code</th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Price</th>
        <th>Total</th>
        <th>Notes</th>
        <th class="smaller no-print">Delivered</th>
        <th id="items_blank_th" class="no-print"></th>

      </tr>

      <% @purchase_order.purchase_items.each do | purchase_item | %>
        <%=render purchase_item %>
      <% end %>
      
      
        <tr id="show_new_purchase_item_link_row" class="no-print">
          <td colspan="7">
            <%=link_to 'Add', '', id: 'show_new_purchase_item_link', class: 'add_fields no-print'%>
          </td>
        </tr>


            <tr id="new_purchase_item_row" class="no-print">
              <td class="item_name"><%= f.text_field :item_name, data: {autocomplete_source: item_names_path}%></td>
              <td class="item_quantity_column small_number"><%= f.number_field :quantity, min: 1%></td>
              <td class="med_number"><%= f.text_field :unit%></td>
              <td class="item_price_column med_number"><%= f.text_field :price%></td>
              <td class="med_number"><%= f.text_field :total, class: "total_field"%></td>
              <td class="notes_column">
                <%= f.text_field :note%>
                <%= f.hidden_field :purchase_order_id %>
              </td>
              <td>
                <%= f.submit "Add", id: 'add_contact_number_submit' %>
              </td>
              <td>                <%= link_to 'Hide', '', id: "hide_new_purchase_item_link", class:"button_link" %></td>
            </tr>
      
      <tr class="no_bg grand_total_row">
        <td colspan="4" class="no_bg no_border txt-right loud">Grand Total: </td>
        <td class="no_bg grand_total txt-left no_border loud">
              <span id="grand_total"><%=number_with_delimiter @purchase_order.grand_total%></span>
        </td>
        <td colspan="3" class="no_border no_bg"></td>
      </tr>
    </table>
  <% end %>
</div>

<% end %>