config/routes.rb
EEGM::Application.routes.draw do
  get "system_updates/index"
  resources :system_configs

  resources :activities
  

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get "purchase_orders/reload_purchase_item/:purchase_item_id" => 'purchase_orders#reload_purchase_item', as: 'reload_purchase_item'
  get "purchase_orders/reload_purchase_item" => 'purchase_orders#reload_purchase_item', as: 'partial_reload_purchase_item'

  get "purchase_orders/update_purchase_items" => 'purchase_orders#update_purchase_items', as: 'partial_update_purchase_items'
  get "purchase_orders/update_purchase_items/:item_delivery_id" => 'purchase_orders#update_purchase_items', as: 'update_purchase_items'
  get "purchase_items/index"
  get "purchase_items/new"
  get "purchase_items/create"
  get "purchase_items/destroy"
  get "purchase_items/update"
  get "purchase_order_contacts/index"
  get "purchase_order_contacts/new"
  get "purchase_order_contacts/create"
  get "purchase_order_contacts/destroy"
  get "purchase_order_contacts/update"
  resources :item_deliveries

  resources :purchase_orders do
    get 'status/:po_status' => "purchase_orders#index", on: :collection, as: 'status'
    get 'print' => 'purchase_orders#print', on: :member
  end

  resources :supplier_items

  resources :items

  resources :suppliers do
    get 'summary', on: :member
  end

  resources :contacts

  resources :phones

  resources :purchase_order_contacts

  resources :purchase_items do
  end

  get 'suppliers/:id/summary/:po_status' => "suppliers#summary", as: 'summary_by_status_supplier'

  get 'latest/price/name', to: 'purchase_items#index', as: 'last_price_purchase_item_name'
  get 'purchase_item/last', to: 'purchase_items#last', as: 'partial_last_purchase_item'
  get 'purchase_item/last/:item_id', to: 'purchase_items#last', as: 'last_purchase_item'

  get 'supplier/names', to: 'suppliers#names'
  get 'contact/names', to: 'contacts#names'
  get 'item/names', to: 'items#names'
  get 'phone/numbers', to: 'phones#numbers'

  root 'purchase_orders#index'

end

app/models/supplier_item.rb
class SupplierItem < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :item
end

app/controllers/supplier_items_controller.rb
class SupplierItemsController < ApplicationController
  before_action :set_supplier_item, only: [:show, :edit, :update, :destroy]

  # GET /supplier_items
  # GET /supplier_items.json
  def index
    @supplier_items = SupplierItem.all
  end

  # GET /supplier_items/1
  # GET /supplier_items/1.json
  def show
  end

  # GET /supplier_items/new
  def new
    @supplier_item = SupplierItem.new
  end

  # GET /supplier_items/1/edit
  def edit
  end

  # POST /supplier_items
  # POST /supplier_items.json
  def create
    @supplier_item = SupplierItem.new(supplier_item_params)

    respond_to do |format|
      if @supplier_item.save
        format.html { redirect_to @supplier_item, notice: 'Supplier item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @supplier_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @supplier_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplier_items/1
  # PATCH/PUT /supplier_items/1.json
  def update
    respond_to do |format|
      if @supplier_item.update(supplier_item_params)
        format.html { redirect_to @supplier_item, notice: 'Supplier item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supplier_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplier_items/1
  # DELETE /supplier_items/1.json
  def destroy
    @supplier_item.destroy
    respond_to do |format|
      format.html { redirect_to supplier_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier_item
      @supplier_item = SupplierItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_item_params
      params.require(:supplier_item).permit(:supplier_id, :item_id, :price, :note)
    end
end

app/helpers/supplier_items_helper.rb
module SupplierItemsHelper
end

app/views/supplier_items/_form.html.erb
<%= form_for(@supplier_item) do |f| %>
  <% if @supplier_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier_item.errors.count, "error") %> prohibited this supplier_item from being saved:</h2>

      <ul>
      <% @supplier_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :supplier_id %><br>
    <%= f.text_field :supplier_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supplier_items/edit.html.erb
<h1>Editing supplier_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier_item %> |
<%= link_to 'Back', supplier_items_path %>

app/views/supplier_items/index.html.erb
<h1>Listing supplier_items</h1>

<table>
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Item</th>
      <th>Price</th>
      <th>Note</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @supplier_items.each do |supplier_item| %>
      <tr>
        <td><%= supplier_item.supplier %></td>
        <td><%= supplier_item.item %></td>
        <td><%= supplier_item.price %></td>
        <td><%= supplier_item.note %></td>
        <td><%= link_to 'Show', supplier_item %></td>
        <td><%= link_to 'Edit', edit_supplier_item_path(supplier_item) %></td>
        <td><%= link_to 'Destroy', supplier_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplier item', new_supplier_item_path %>

app/views/supplier_items/new.html.erb
<h1>New supplier_item</h1>

<%= render 'form' %>

<%= link_to 'Back', supplier_items_path %>

app/views/supplier_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @supplier_item.supplier %>
</p>

<p>
  <strong>Item:</strong>
  <%= @supplier_item.item %>
</p>

<p>
  <strong>Price:</strong>
  <%= @supplier_item.price %>
</p>

<p>
  <strong>Note:</strong>
  <%= @supplier_item.note %>
</p>

<%= link_to 'Edit', edit_supplier_item_path(@supplier_item) %> |
<%= link_to 'Back', supplier_items_path %>