config/routes.rb
EEGM::Application.routes.draw do
  get "system_updates/index"
  resources :system_configs

  resources :activities
  

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get "purchase_orders/reload_purchase_item/:purchase_item_id" => 'purchase_orders#reload_purchase_item', as: 'reload_purchase_item'
  get "purchase_orders/reload_purchase_item" => 'purchase_orders#reload_purchase_item', as: 'partial_reload_purchase_item'

  get "purchase_orders/update_purchase_items" => 'purchase_orders#update_purchase_items', as: 'partial_update_purchase_items'
  get "purchase_orders/update_purchase_items/:item_delivery_id" => 'purchase_orders#update_purchase_items', as: 'update_purchase_items'
  get "purchase_items/index"
  get "purchase_items/new"
  get "purchase_items/create"
  get "purchase_items/destroy"
  get "purchase_items/update"
  get "purchase_order_contacts/index"
  get "purchase_order_contacts/new"
  get "purchase_order_contacts/create"
  get "purchase_order_contacts/destroy"
  get "purchase_order_contacts/update"
  resources :item_deliveries

  resources :purchase_orders do
    get 'status/:po_status' => "purchase_orders#index", on: :collection, as: 'status'
    get 'print' => 'purchase_orders#print', on: :member
  end

  resources :supplier_items

  resources :items

  resources :suppliers do
    get 'summary', on: :member
  end

  resources :contacts

  resources :phones

  resources :purchase_order_contacts

  resources :purchase_items do
  end

  get 'suppliers/:id/summary/:po_status' => "suppliers#summary", as: 'summary_by_status_supplier'

  get 'latest/price/name', to: 'purchase_items#index', as: 'last_price_purchase_item_name'
  get 'purchase_item/last', to: 'purchase_items#last', as: 'partial_last_purchase_item'
  get 'purchase_item/last/:item_id', to: 'purchase_items#last', as: 'last_purchase_item'

  get 'supplier/names', to: 'suppliers#names'
  get 'contact/names', to: 'contacts#names'
  get 'item/names', to: 'items#names'
  get 'phone/numbers', to: 'phones#numbers'

  root 'purchase_orders#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_reader :label
	  has_many :supplier_items
  	has_many :suppliers, through: :supplier_items
    validates :name, uniqueness: true

    def css_id
      "item_#{id}"
    end

  	def label
  		self.name
  	end

  	def last_pi
  		PurchaseItem.last_item(self.id)
  	end

  	def last_po
  		if last_pi.class == PurchaseItem
  			last_pi.purchase_order
  		else
  			nil
  		end
  	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.paginate(:page => params[:page]).order(name: :asc)
  end

  def names
    @items = Item.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @items.to_json(methods: :label)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { respond_with_bip @item }
      else
        format.html { render action: 'edit' }
        format.json { respond_with_bip @item }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h2 class="titleize">Editing item</h2>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%=javascript_tag do %>

$(document).ready(function(){
    $('#item_list').dataTable( {
          bJQueryUI: true,
        iDisplayLength: 100,
        "sPaginationType": "full_numbers",
    } );
});

<% end %>

<h2 class="titleize">Items List</h1>

<%= will_paginate @items %>

<table id="item_list">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last PO Price</th>
      
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= number_with_delimiter number_with_precision(item.last_pi.try(:price), precision: 2)%>
        </td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>

        <td>
          <% if item.last_po %>
            <%= link_to('View Last PO', purchase_order_path(item.last_po))  %>
          <% else %>
            <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }%> 
          <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @items %>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>